package edu.mum.volunteers.models;

public enum ProjectStatus {
	NOT_STARTED,ZERO_PERCENT,TEN_PERCENT,TWENTY_PERCENT,THIRTY_PERCENT,FOURTY_PERCENT,FIFTY_PERCENT,
	SIXTY_PERCENT,SEVENTY_PERCENT,EIGHT_PERCENT,NINETY_PERCENT,HUNDRED_PERCENT,COMPLETED
}
